module ParserAndCompiler.Constants where
import ParserAndCompiler.Types as Types

{- header -}
headerPrefix    = "{"++"-GENERATED BY GRAPHICALELM " 
headerPostfix   = commentEnd

makeHeader: Types.Version -> String
makeHeader v = headerPrefix ++ Types.showVersion v ++ headerPostfix

{- misc -}
startMisc       = "{-START MISC-}"
endMisc         = "{-END MISC-}"

{- nodes -}
nameObfuscator  = "PrivateDon'tUse"

codeQuoteOpen   = "#####$#"
codeQuoteClose  = "#$#####"

commentStart = "{-"
commentEnd = "-}"

languageMarker = "_language_"
baseCodeMarker = "_base_code_"
parentsMarker  = "_parents_"
